FROM node:18-alpine3.19

WORKDIR /srv
EXPOSE 7000
ENV RESPONSETIMEOUT=
ENV PORT=
ENV MIN_SEED=
ENV MAX_RESULTS=
ENV MAX_SIZE=
ENV JACKETT_HOST=
ENV JACKETT_RTIMEOUT=
ENV JACKETT_OTIMEOUT=
COPY . .
RUN npm install

CMD ["node", "index.js"]
