FROM node:18-alpine3.19

WORKDIR /srv 
EXPOSE 7000

# Config vars 
ENV INTERVAL=
ENV RESPONSE_TIMEOUT=
ENV PORT=
ENV MIN_SEED=
ENV MAX_RESULTS=
ENV MAX_SIZE=10GB
ENV JACKETT_HOSTS=
ENV JACKETT_APIKEYS=
ENV JACKETT_RTIMEOUT=5000
ENV SEARCH_BY_TYPE=
ENV DEBUG=
ENV DOWNLOAD_TORRENT_QUEUE=10
ENV ADD_BEST_TRACKERS=true
ENV ADD_RUSSIAN_TRACKERS=
ENV ADD_EXTRA_TRACKERS=
ENV PARSE_TORRENT_FILES=
ENV REMOVE_BLACKLIST_TRACKERS=true
ENV INDEXER_FILTERS=
ENV ADDON_NAME=
ENV ADDITIONAL_SOURCES=aHR0cHM6Ly90b3JyZW50aW8uc3RyZW0uZnVuL3Byb3ZpZGVycz15dHMsZXp0dixyYXJiZywxMzM3eCx0aGVwaXJhdGViYXksa2lja2Fzc3RvcnJlbnRzLHRvcnJlbnRnYWxheHksbWFnbmV0ZGwsaG9ycmlibGVzdWJzLG55YWFzaSx0b2t5b3Rvc2hvLGFuaWRleHxzb3J0PXNlZWRlcnN8cXVhbGl0eWZpbHRlcj1zY3IsY2FtfGxpbWl0PTV8c2l6ZWZpbHRlcj01R0Ivc3RyZWFtL3x8VG9ycmVudGlv,aHR0cHM6Ly90aGVwaXJhdGViYXktcGx1cy5zdHJlbS5mdW4vc3RyZWFtL3x8VFBCKw==,aHR0cHM6Ly90b3JyZW50aW8uYXJhZWMuY29tL3Byb3ZpZGVycz15dHMsZXp0dixyYXJiZywxMzM3eCx0aGVwaXJhdGViYXksa2lja2Fzc3RvcnJlbnRzLHRvcnJlbnRnYWxheHksbWFnbmV0ZGwsaG9ycmlibGVzdWJzLG55YWFzaSx0b2t5b3Rvc2hvLGFuaWRleHxzb3J0PXNlZWRlcnN8cXVhbGl0eWZpbHRlcj1zY3IsY2FtLHVua25vd258bGltaXQ9MTB8c2l6ZWZpbHRlcj01R0Ivc3RyZWFtL3x8VG9ycmVudGlvLXNo
ENV CACHE_INDEXERS_TIME=1440
ENV CACHE_RESULTS_TIME=10080
ENV TMDB_APIKEY=
ENV UPDATE_TRACKERS_INTERVAL=

# dont need
ENV NODE_ENV=production

ARG VERSION=testing
LABEL org.opencontainers.image.source=https://github.com/tsaridas/jackett-stremio
LABEL org.opencontainers.image.description="Jackett Local Addon for Stremio"
LABEL org.opencontainers.image.licenses=MIT
LABEL version=${VERSION}


COPY . .
RUN chmod +x start.sh
RUN apk update && apk upgrade && rm -rf /var/cache/apk/*
RUN npm install --no-fund --omit=dev


ENTRYPOINT ["./start.sh"]
